name: deploy about dev profile
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SLACK_DEPLOY_NOTIFICATION_URL: ${{ secrets.SLACK_DEPLOY_NOTIFICATION_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Configure to AWS
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=BuilzerLogApp-dev" \
            --parameters "commands='#!/bin/bash
            rm -rf builzer-log
            git clone https://CokeLee777:${{ secrets.GIT_ACCESS_TOKEN }}@github.com/Builzer/builzer-log.git
            cd builzer-log
            docker-compose up setup
            docker-compose up -d'" \
            --comment "Deploying Docker container to EC2 via SSM" \
            --timeout-seconds 600
  success-notification:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    if: success()
    steps:
      - name: Send Successful deployment message to slack channel
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#배포-모니터링
          \", \"username\": \"배포 완료 알림\", \"text\": \"[환경]: dev\n[모듈]: builzer-log\"}" ${{ env.SLACK_DEPLOY_NOTIFICATION_URL }}
  failure-notification:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    if: failure()
    steps:
      - name: Send Failure deployment message to slack channel
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#배포-모니터링
          \", \"username\": \"배포 실패 알림\", \"text\": \"[환경]: dev\n[모듈]: builzer-log\"}" ${{ env.SLACK_DEPLOY_NOTIFICATION_URL }}